language: python
python:
  - "3.5"
env:
  global:
    - ABCDB_SECRET_KEY='travis_test_database_key_v&+rhgwyl^=cnorq@m-el*nb*'
    - ABCDB_DEPLOYMENT='development'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install graphviz -y
install:
  - pip install -q -r requirements.txt
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$PATH:~/.cargo/bin"
  - rustup toolchain install stable
  - cargo build
script:
  - python manage.py makemigrations && python manage.py test main --exclude-tag fetch
